<a href="https://colab.research.google.com/github/Alexey-919/Alexey-919/blob/master/Project_2_%D0%9D%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA_%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [ ]:
!pip install ipykernel

In [2]:
import pandas as pd
import psycopg2

In [64]:
# вставьте сюда параметры подключения из юнита 1. Работа с базой данных из Python
DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

In [4]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [ ]:
# текст запроса
query_3_1 = f'''select *
           from public.VACANCIES
'''
df_VACANCIES = pd.read_sql_query(query_3_1, connection)

In [10]:
# результат запроса
df_VACANCIES['id'].nunique()

49197

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [ ]:
# текст запроса
query_3_2 = f'''select *
           from public.EMPLOYERS
        '''
df_EMPLOYERS = pd.read_sql_query(query_3_2, connection)

In [12]:
# результат запроса
df_EMPLOYERS['id'].nunique()

23501

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [ ]:
# текст запроса
query_3_3 = f'''select *
           from public.AREAS
        '''
df_AREAS = pd.read_sql_query(query_3_3, connection)

In [14]:
# результат запроса
df_AREAS['name'].nunique()

1362

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [ ]:
# текст запроса
query_3_4 = f'''select *
           from public.INDUSTRIES
        '''
df_INDUSTRIES = pd.read_sql_query(query_3_4, connection)

In [16]:
# результат запроса
df_INDUSTRIES['id'].nunique()

294

***

In [ ]:
# выводы по предварительному анализу данных
# Здесь мы посмотрели на количество вакансий, представленных в базе, количество работодателей, в каком количестве регионов
# предлагается работа, а также сколько сфер деятельности.

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [ ]:
# текст запроса
query_4_1 = f'''
select a.name, count(v.id)
from public.areas a
join public.vacancies v ON a.id = v.area_id
group by a.id
order by 2 desc
'''
df_4_1 = pd.read_sql_query(query_4_1, connection)

In [20]:
# результат запроса
df_4_1

                         name  count
0                      Москва   5333
1             Санкт-Петербург   2851
2                       Минск   2112
3                 Новосибирск   2006
4                      Алматы   1892
..                        ...    ...
764                    Кизляр      1
765                    Джизак      1
766                    Эртиль      1
767                  Арсеньев      1
768  Тура (Красноярский край)      1

[769 rows x 2 columns]

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [ ]:
# текст запроса
query_4_2 = f'''select count(v.id)
from public.vacancies v
where v.salary_from is not NULL or v.salary_to is not NULL
'''
df_4_2 = pd.read_sql_query(query_4_2, connection)

In [22]:
# результат запроса
df_4_2

   count
0  24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [ ]:
# текст запроса
query_4_3 = f'''select
avg(v.salary_from) avg_from,
avg(v.salary_to) avg_to
from public.vacancies v'''
df_4_3 = pd.read_sql_query(query_4_3, connection)

In [39]:
# результат запроса
print(df_4_3['avg_from'].round())
print(df_4_3['avg_to'].round())

0    71065.0
Name: avg_from, dtype: float64
0    110537.0
Name: avg_to, dtype: float64

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [ ]:
# текст запроса
query_4_4 = f'''select schedule, employment, count(id)
from public.vacancies
group by schedule, employment
order by count(id) desc
'''
df_4_4 = pd.read_sql_query(query_4_4, connection)

In [41]:
# результат запроса
df_4_4

            schedule           employment  count
0        Полный день     Полная занятость  35367
1   Удаленная работа     Полная занятость   7802
2      Гибкий график     Полная занятость   1593
3   Удаленная работа  Частичная занятость   1312
4     Сменный график     Полная занятость    940
5        Полный день           Стажировка    569
6     Вахтовый метод     Полная занятость    367
7        Полный день  Частичная занятость    347
8      Гибкий график  Частичная занятость    312
9        Полный день     Проектная работа    141
10  Удаленная работа     Проектная работа    133
11     Гибкий график           Стажировка    116
12    Сменный график  Частичная занятость    101
13  Удаленная работа           Стажировка     64
14     Гибкий график     Проектная работа     18
15    Сменный график           Стажировка     12
16    Вахтовый метод     Проектная работа      2
17    Сменный график     Проектная работа      1

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [44]:
# текст запроса
query_4_5 = f'''select experience,
count(experience)
from public.vacancies
group by 1
order by count(experience) '''
df_4_5 = pd.read_sql_query(query_4_5, connection)

<ipython-input-44-598cb0db993d>:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_5 = pd.read_sql_query(query_4_5, connection)

In [45]:
# результат запроса
df_4_5

           experience  count
0         Более 6 лет   1337
1           Нет опыта   7197
2       От 3 до 6 лет  14511
3  От 1 года до 3 лет  26152

***

In [46]:
# выводы по детальному анализу вакансий
# В данном разборе все достаточно понятно, взглянули на количество вакансий представленных в городах, как и ожидалось лидерами
# оказались столицы. Посмотрели на зарплату, которая предлагается работодателями (какой средний минимум и средний максимум представлен).
# Посмотрели на востребованность соискателями типа трудоустройства и рабочего графика. И взглянули на количество вакансий в зависимости
# от требуемого опыта, естественно лидером оказался самый молодой, от 1 года до 3 лет.

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [ ]:
# текст запроса
query_5_1 = f'''(select
e.name, count(v.id)
from public.employers e
LEFT JOIN public.vacancies v ON e.id = v.employer_id
group by e.id
ORDER BY 2 desc
limit 1)
UNION ALL
(select
e.name, count(v.id)
from public.employers e
LEFT JOIN public.vacancies v ON e.id = v.employer_id
group by e.id
ORDER BY 2 desc
offset 4
limit 1)
ORDER BY 2 desc
'''
df_5_1 = pd.read_sql_query(query_5_1, connection)

In [62]:
# результат запроса
df_5_1

            name  count
0         Яндекс   1933
1  Газпром нефть    331

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [63]:
# текст запроса
query_5_2 = f'''select a.name, COUNT(distinct e.id) as "Количество_работодателей", count(distinct v.id) as "Количество_выкансий"
from public.areas a
join public.EMPLOYERS e ON a.id = e.area
left join public.vacancies v ON a.id = v.area_id
group by a.id
ORDER BY count(v.id), COUNT(distinct e.id) DESC
'''
df_5_2 = pd.read_sql_query(query_5_2, connection)

<ipython-input-63-30c36683ba8d>:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_2 = pd.read_sql_query(query_5_2, connection)

In [65]:
# результат запроса
df_5_2

                   name  Количество_работодателей  Количество_выкансий
0                Россия                       410                    0
1             Казахстан                       207                    0
2    Московская область                        75                    0
3    Краснодарский край                        19                    0
4              Беларусь                        18                    0
..                  ...                       ...                  ...
649         Новосибирск                       573                 2006
650              Алматы                       721                 1892
651               Минск                      1115                 2112
652     Санкт-Петербург                      2217                 2851
653              Москва                      5864                 5333

[654 rows x 3 columns]

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [ ]:
# текст запроса
query_5_3 = f'''select e.name, count(distinct v.area_id)
from public.employers e
JOIN public.vacancies v ON e.id = v.employer_id
GROUP BY e.id
ORDER BY 2 DESC'''
df_5_3 = pd.read_sql_query(query_5_3, connection)

In [67]:
# результат запроса
df_5_3

                                         name  count
0                                      Яндекс    181
1                                  Ростелеком    152
2                                  Спецремонт    116
3                      Поляков Денис Иванович     88
4                                   ООО ЕФИН      71
...                                       ...    ...
14901                            НПП Авиатрон      1
14902              Центр дистанционных торгов      1
14903  Городские Телекоммуникационные Системы      1
14904                       Введенский, Отель      1
14905              Группа Компаний Автоимпорт      1

[14906 rows x 2 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [ ]:
# текст запроса
query_5_4 = f'''select count(*)
from public.EMPLOYERS as e
left join EMPLOYERS_INDUSTRIES as ee ON e.id = ee.employer_id
where ee.industry_id is NULL
'''
df_5_4 = pd.read_sql_query(query_5_4, connection)

In [69]:
# результат запроса
df_5_4

   count
0   8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [ ]:
# текст запроса
query_5_5 = f''' select e.name, count(ee.industry_id)
from public.employers as e
JOIN public.employers_industries as ee ON e.id = ee.employer_id
group by e.id
having count(ee.industry_id) = 4
ORDER BY e.name
offset 2
limit 1
'''
df_5_5 = pd.read_sql_query(query_5_5, connection)

In [71]:
# результат запроса
df_5_5

   name  count
0  2ГИС      4

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [ ]:
# текст запроса
query_5_6 = f''' select count(*)
from public.employers_industries as e
join public.industries as i ON e.industry_id = i.id
where i.name = 'Разработка программного обеспечения'
'''
df_5_6 = pd.read_sql_query(query_5_6, connection)

In [73]:
# результат запроса
df_5_6

   count
0   3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8).

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [ ]:
# код для получения списка городов-милионников

In [ ]:
# текст запроса
big_city = (
    "Москва", "Санкт-Петербург", "Новосибирск",
    "Екатеринбург", "Казань", "Нижний Новгород",
    "Красноярск", "Челябинск", "Самара", "Уфа",
    "Ростов-на-Дону", "Омск", "Краснодар",
    "Воронеж", "Пермь", "Волгоград"
)
# код запроса представляет из себя строковую переменную
query_5_7 = f'''(SELECT
                a.name,
                count(*) cnt
         from employers e
         join vacancies v on e.id = v.employer_id
         join areas a on a.id = v.area_id
            WHERE e.name = 'Яндекс' and a.name in {big_city}
            GROUP BY a.id
            ORDER BY 2 ASC)

            UNION ALL

            (SELECT
                'TOTAL',
                COUNT (*) "Общ кол-во вакансий в городах-миллионниках"
            FROM public.vacancies v
                JOIN public.employers e ON e.id = v.employer_id
                JOIN public.areas a ON a.id = v.area_id
            WHERE e.name = 'Яндекс' and a.name in {big_city})
            ORDER BY 2 DESC

        '''

df_5_7 = pd.read_sql_query(query_5_7, connection)

In [75]:
# результат запроса
df_5_7

               name  cnt
0             TOTAL  485
1            Москва   54
2   Санкт-Петербург   42
3      Екатеринбург   39
4   Нижний Новгород   36
5       Новосибирск   35
6           Воронеж   32
7         Краснодар   30
8               Уфа   26
9            Самара   26
10           Казань   25
11            Пермь   25
12   Ростов-на-Дону   25
13        Волгоград   24
14       Красноярск   23
15        Челябинск   22
16             Омск   21

***

In [ ]:
# выводы по анализу работодателей
# Здесь мы уже более детально рассматриваем работадателей и вакансии, которые они предлагают. Применяем различные фильтра, для более
# полного понимания спицифики задания, как в принципе и ожидалось крупные компания публикуют большее количество вакансий и представлены
# в большем количестве городов.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [ ]:
# текст запроса
query_6_1 = f'''select count(*)
from public.vacancies
where (name ILIKE '%data%') OR (name ILIKE '%данн%')
'''
df_6_1 = pd.read_sql_query(query_6_1, connection)

In [77]:
# результат запроса
df_6_1

   count
0   1771

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста?
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [ ]:
# текст запроса
query_6_2 = f'''select count(*)
from public.vacancies
where ((name ILIKE '%data scientist%') OR (name ILIKE '%data science%') OR (name ILIKE '%исследователь данных%')
  OR ((name ILIKE '%ML%') AND (name NOT ILIKE '%HTML%'))
  OR (name ILIKE '%machine learning%') OR (name ILIKE '%машинн%обучен%')
  AND (key_skills IS NOT NULL))
  AND(name ILIKE '%junior%' OR experience ILIKE '%Нет опыта%' OR employment ILIKE '%Стажировка%')
'''
df_6_2 = pd.read_sql_query(query_6_2, connection)

In [79]:
# результат запроса
df_6_2

   count
0     51

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [ ]:
# текст запроса
query_6_3 = f'''select count(*)
from public.vacancies
where ((name ILIKE '%data scientist%') OR (name ILIKE '%data science%') OR (name ILIKE '%исследователь данных%')
  OR ((name LIKE '%ML%') AND (name NOT ILIKE '%HTML%'))
  OR (name ILIKE '%machine learning%') OR (name ILIKE '%машинн%обучен%'))
  AND (key_skills ILIKE '%SQL%' OR key_skills ILIKE '%postgres%')
'''
df_6_3 = pd.read_sql_query(query_6_3, connection)

In [81]:
# результат запроса
df_6_3

   count
0    201

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [ ]:
# текст запроса
query_6_4 = f'''select count(*)
from public.vacancies
where ((name ILIKE '%data scientist%') OR (name ILIKE '%data science%') OR (name ILIKE '%исследователь данных%')
  OR ((name LIKE '%ML%') AND (name NOT ILIKE '%HTML%'))
  OR (name ILIKE '%machine learning%') OR (name ILIKE '%машинн%обучен%'))
  AND (key_skills ILIKE '%Python%')
'''
df_6_4 = pd.read_sql_query(query_6_4, connection)

In [83]:
# результат запроса
df_6_4

   count
0    351

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [ ]:
# текст запроса
query_6_5 = f'''SELECT ROUND(AVG(coalesce(1, null) + (length(key_skills) - length(REPLACE(key_skills, CHR(9), ''))))::numeric, 2)

FROM public.vacancies v
WHERE ((name ILIKE '%data scientist%') OR (name ILIKE '%data science%')
OR (name ILIKE '%исследователь данных%') OR ((name LIKE '%ML%') AND (name NOT ILIKE '%HTML%'))
OR (name ILIKE '%machine learning%') OR (name ILIKE '%машинн%обучен%') AND (key_skills IS NOT NULL))'''

df_6_5 = pd.read_sql_query(query_6_5, connection)

In [85]:
# результат запроса
df_6_5

   round
0   6.41

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*).

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [ ]:
# текст запроса
query_6_6 = f'''SELECT experience,
round(avg(coalesce((salary_from+salary_to)/2, salary_from, salary_to)), 0)
FROM public.vacancies
WHERE ((name ILIKE '%data scientist%') OR (name ILIKE '%data science%')
OR (name ILIKE '%исследователь данных%') OR ((name LIKE '%ML%') AND (name NOT ILIKE '%HTML%'))
OR (name ILIKE '%machine learning%') OR (name ILIKE '%машинн%обучен%') AND (key_skills IS NOT NULL))
AND ((salary_from IS NOT NULL) OR (salary_to IS NOT NULL))
and (experience = 'От 3 до 6 лет')
group by experience'''

df_6_6 = pd.read_sql_query(query_6_6, connection)

In [87]:
# результат запроса
df_6_6

      experience     round
0  От 3 до 6 лет  243115.0

In [88]:
connection.close()

***

In [ ]:
# выводы по предметному анализу
# Здесь мы уже углубились непосредственно в профессии и во сколько они оцениваются на рынке труда. В основном взглянули как оценивается
# профессия DS с различными вариациями опыта и навыков, а также сколько вакансий представлено на рынке труда в зависмости
#  от тех же параметров.

# Общий вывод по проекту

In [ ]:
# подведем итог исследования, обобщите выводы
# здесь можно (это будет плюсом) провести дополнительные исследования данных, сделать прогнозы, продумать варианты продолжения исследования

Мы провели плодотворый анализ вакансий, применив при этом навыки работы с базами данных. Посмотрели в целом, на то, как выглядит рынок вакансий в разрезе городов, зарплат и других различных парамеров. А также увидели какие требования предъявляются к специалисту DS  и как это профессия оплачивается.